name: Django-app workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check bash
      run: |
        which bash
        bash --version

    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # Выполняет деплой
          cd ${{ secrets.PATH }}
          source venv/bin/activate
          git pull –no-rebase
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          sudo service ${{ secrets.GUNICORN }} restart
          sudo service nginx restart
